#!/usr/bin/env bash
#
sudo npm i -g bash-language-server

#docker
sudo npm install -g dockerfile-language-server-nodejs

#emmet
sudo npm install -g emmet-ls

#gopls
go install golang.org/x/tools/gopls@latest

#ccsls jsonls eslint html
sudo npm i -g vscode-langservers-extracted

sudo npm i -g sql-language-server

sudo npm install -g @tailwindcss/language-server

sudo npm install -g typescript typescript-language-server

#vue
sudo npm install -g vls

sudo npm install -g graphql-language-service-cli

sudo yarn global add yaml-language-server

# elm
npm install -g elm elm-test elm-format @elm-tooling/elm-language-server
