#!/usr/bin/env bash
echo "run install"

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/lua/zoom

# link wholesale
for f in `find . -regex ".*\.vim$"`; do
    echo $f
    rm -rf ~/.config/nvim/$f
    ln -s ~/mydotfiles/$f ~/.config/nvim/$f
done

for f in `find ./lua -regex ".*\.lua$"`; do
    echo $f
    rm -rf ~/.config/nvim/$f
    ln -s ~/mydotfiles/$f ~/.config/nvim/$f
done
