#!/usr/bin/env bash
sudo npm i -g bash-language-server

sudo npm i -g vscode-langservers-extracted

sudo npm install -g dockerfile-language-server-nodejs

sudo npm install -g emmet-ls

go install golang.org/x/tools/gopls@latest

sudo npm i -g vscode-langservers-extracted

sudo npm i -g sql-language-server

sudo npm install -g @tailwindcss/language-server

sudo npm install -g typescript typescript-language-server

sudo npm install -g vls

sudo npm install -g graphql-language-service-cli

sudo npm i -g vscode-langservers-extracted
