#!/usr/bin/env bash
npm i -g bash-language-server

npm i -g vscode-langservers-extracted

npm install -g dockerfile-language-server-nodejs

npm install -g emmet-ls

go install golang.org/x/tools/gopls@latest

npm i -g vscode-langservers-extracted

npm i -g sql-language-server

npm install -g @tailwindcss/language-server

npm install -g typescript typescript-language-server

npm install -g vls

npm install -g graphql-language-service-cli

npm i -g vscode-langservers-extracted

