#!/bin/sh

function fzfPrjdir() {
    cat "$MYFILES/prjdirs.txt" 
    echo "select a project dir"
    prj=$(cat "$MYFILES/prjdirs.txt" | fzf)
    [ -z "$prj" ] && exit 1

    echo -e "$prj"
    exit 0
}

function dmenuPrjdir() {
    cat "$MYFILES/prjdirs.txt" 
    prj=$(cat "$MYFILES/prjdirs.txt" | dmenu -l 10)
    [ -z "$prj" ] && exit 1

    echo -e "$prj"
    exit 0
}
