#!/bin/sh

function fzfDKCdir() {
    echo "select a docker-compose workspace"
    prj=$(cat "$MYFILES/workspaces.txt" | fzf)
    [ -z "$prj" ] && exit 1

    echo -e "$prj"
    exit 0
}

function dmenuDKCdir() {
    prj=$(cat "$MYFILES/workspaces.txt" | dmenu -i -p "dkc workspace" -l 10)
    [ -z "$prj" ] && exit 1

    echo -e "$prj"
    exit 0
}
