#!/bin/sh

function fzfPrjdir() {
    prj=$(fzf < "$MYFILES/prjdirs.txt")
    [ -z "$prj" ] && exit 1

    echo -e "$prj"
    exit 0
}

function dmenuPrjdir() {
    prj=$(dmenu -i -l 10 < "$MYFILES/prjdirs.txt" )
    [ -z "$prj" ] && exit 1

    echo -e "$prj"
    exit 0
}
