#!/bin/sh

function getDKCdirF() {
    prj=$(cat "$MYFILES/workspaces.txt" | fzf)
    [ -z "$prj" ] && exit 1

    echo -e "$prj"
    exit 0
}

function getDKCdir() {
    prj=$(cat "$MYFILES/workspaces.txt" | dmenu -l 10)
    [ -z "$prj" ] && exit 1

    echo -e "$prj"
    exit 0
}
