#!/usr/bin/env bash
#d=(~/projects $CPM_CPALL_ROOT/services $CPM_CPR_ROOT/services)
d=(~/projects)

p=$(fd -H -x echo {//} \; ^\.git$ ${d[*]})

if [ -z $1 ]; then
    p=$(echo -e "$p" | fzf --preview="tree -L 1 {}")
else
    p=$(echo -e "$p" | fzf --preview="tree -L 1 {}" -q $1)
fi

[ -z "$p" ] && exit 1
echo $p
