#!/usr/bin/env bash

picker="dmenu"
case $1 in 
    -dmenu)
        picker="dmenu"
        ;;
    -fzf)
        picker="fzf"
        ;;
esac

selectFromPipe(){
    case $picker in
        dmenu)
            cat - | dmenu -i
            exit 0
            ;;
        fzf)
            cat -| fzf
            exit 0
            ;;
    esac
}

xrandr | rg "\*" | sed -r -e "s/([0-9])\.([0-9]+)/\1/g; s/ +/\n/g;" | rg "^[0-9]+$" | selectFromPipe | xargs xrandr -r
