#!/bin/sh
r=${0%/*}
source "$r/functions/get-prj-dir"

target=$(fzfPrjdir || exit 1)

t="${target%% *}"
wdir="${target##* }"

#get scripts file that start with number
s=$(ls -1 ${wdir} | fzf )
[ -z $s ] && exit 1

cd "$wdir/$s"
tmux new -A -s "$t-$s"
