#!/bin/sh
r=${0%/*}
source "$r/functions/get-dkc-dir"

target=$(getDKCdir || exit 1)

t=$(echo "$target" | awk '{print $1}')
wdir=$(echo "$target" | awk '{print $2}')

#get scripts file that start with number
s=$(ls -1 ${wdir}/scripts | grep -E -e '^[0-9]' | dmenu -l 10)
[ -z $s ] && exit 2

alacritty --working-directory="$wdir" -t "$t scripts" -e "./scripts/$s" </dev/null &>/dev/null & disown
